routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\DropdownController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [EmployeeController::class, 'index']);

Route::name('employee.')->group(function(){
    Route::get('/employee', [EmployeeController::class, 'index'])->name('index');
    Route::post('/employee/list', [EmployeeController::class, 'listEmployee'])->name('list');
    Route::post('/employee/store', [EmployeeController::class, 'store'])->name('store');
    Route::get('/employee/{employee}/edit', [EmployeeController::class, 'edit'])->name('edit');
    Route::post('/employee/{employee}/edit', [EmployeeController::class, 'update'])->name('update');
    Route::delete('/employee/{employee}', [EmployeeController::class, 'delete'])->name('delete');
});

Route::prefix('dropdown')->group(function(){
    Route::post('province', [DropdownController::class, 'province']);
    Route::post('regency', [DropdownController::class, 'regency']);
    Route::post('position', [DropdownController::class, 'positions']);
    Route::post('bank', [DropdownController::class, 'bank']);
});

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Traits\Filter\Filterable;

class Employee extends Model
{
    use HasFactory, Filterable;

    protected $guarded = [];
}

app/Models/Filter/EmployeeFilter.php
<?php

namespace App\Models\Filter;

use App\Traits\Filter\Filter;
use Illuminate\Database\Eloquent\Builder;

class EmployeeFilter extends Filter
{
    public function firstName($firstName): Builder
    {
        return $this->builder->where('first_name', 'like' ,'%'.$firstName.'%');
    }

    public function lastName($lastName): Builder
    {
        return $this->builder->where('last_name', 'like' ,'%'.$lastName.'%');
    }

    public function positionId($positionId): Builder
    {
        return $this->builder->where('position_id', $positionId);
    }
}

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];
}

app/Models/Province.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    use HasFactory;

    public function regencies()
    {
        return $this->hasMany(Regency::class);
    }
}

app/Models/Regency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Regency extends Model
{
    use HasFactory;

    public function province()
    {
        return $this->belongsTo(Province::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DropdownController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Province;
use App\Models\Regency;
use App\Models\Position;
use App\Models\Bank;
use App\Models\Filter\PositionFilter;

class DropdownController extends Controller
{
    public function province()
    {
        $provinces = Province::pluck('name', 'id');

        return response()->json($provinces);
    }

    public function regency(Request $request)
    {
        $regencies = Regency::where('province_id', $request->provinceId)->pluck('name', 'id');

        return response()->json($regencies);
    }

    public function positions(Request $request)
    {
        $positions = Position::pluck('name', 'id');

        return response()->json($positions);
    }

    public function bank(Request $request)
    {
        $banks = Bank::pluck('name', 'id');

        return response()->json($banks);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Position;
use App\Models\Employee;
use App\Models\Filter\EmployeeFilter;
use App\Http\Requests\Employee\StoreRequest;
use App\Http\Requests\Employee\UpdateRequest;

class EmployeeController extends Controller
{
    public function index(Request $request)
    {
        $positions = Position::all();

        return view('pages.employee.index', compact('positions'));
    }

    public function listEmployee(Request $request)
    {
        $employees = Employee::filter(new EmployeeFilter($request))
                                   ->paginate($request->per_page ?? 12)->withQueryString();

        return response()->json([
            'employees' => $employees
        ]);
    }

    public function store(StoreRequest $request)
    {
        $employee = Employee::create($request->datas());

        return response()->json([
            'employee' => $employee
        ]);
    }

    public function edit(Employee $employee)
    {
        return response()->json($employee);
    }

    public function update(Employee $employee, UpdateRequest $request)
    {
        $employee = $employee->update($request->datas());

        return response()->json([
            'employee' => $employee
        ]);
    }

    public function delete(Employee $employee)
    {
        $employee->delete();

        return response()->json([
            'status' => 'Ok'
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layout.app');
    }
}

app/View/Components/Header.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Header extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.header');
    }
}

app/View/Components/Sidebar.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Sidebar extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.sidebar');
    }
}

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <meta name="description" content="Smarthr - Bootstrap Admin Template">
        <meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern, accounts, invoice, html5, responsive, CRM, Projects">
        <meta name="author" content="Dreamguys - Bootstrap Admin Template">
        <meta name="robots" content="noindex, nofollow">
        <title>PT Juke Solusi Teknologi</title>
        <meta name="csrf-token" content="{{ csrf_token() }}">
        
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{{ asset('assets/orange/img/logo.png') }}">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/bootstrap.min.css') }}">
        
        <!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/font-awesome.min.css') }}">
        
        <!-- Lineawesome CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/line-awesome.min.css') }}">

        @yield('style')
        
        <!-- Main CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/style.css') }}">
        
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="assets/js/html5shiv.min.js"></script>
            <script src="assets/js/respond.min.js"></script>
        <![endif]-->
        <style>
            .header {
                /* background: linear-gradient(to right, #a10000 0%, #f31330 100%) !important; */
                background:white !important;
                box-shadow: 0 5px 5px 0 rgb(0 0 0 / 30%) !important;
            }
            .header-left {
                background-color: #ffffff !important; /* #ffffff */
            }
            .sidebar {
                background-color: #075cd4 !important;
            }
            .sidebar-menu li a { 
                color: #e5e5e5 !important;
            }
            .user-menu.nav > li > a {
                color: #000;
            }
            .top-nav-search .form-control { 
                border-color: #b5aeae !important;
                color: #000;
            }
            .top-nav-search .btn {
                color: #000 !important;
            }
            .top-nav-search ::placeholder {
                color: #000 !important;
            }
            .top-nav-search font {
                color: #000 !important;
            }
            .bar-icon span {
                background-color:#000 !important;
            }
            .page-title-box h3 { 
                color: #000 !important;
            }
        </style>
        <!-- Scripts -->
        
    </head>
    <body>
        <!-- Main Wrapper -->
        <div id="app" class="main-wrapper">
        
            <!-- Header -->
            <x-header></x-header>
            <!-- /Header -->
            
            <!-- Sidebar -->
            <x-sidebar></x-sidebar>
            <!-- /Sidebar -->
            
            <!-- Page Wrapper -->
            <div class="page-wrapper">
                {{ $slot }}
            </div>		
            <!-- /Page Wrapper -->
            
            <!-- /Main Wrapper -->
        
        </div>
        <!-- /Main Wrapper -->
        
        <!-- jQuery -->
        <script src="{{ asset('assets/orange/js/jquery-3.2.1.min.js') }}"></script>
        
        <!-- Bootstrap Core JS -->
        <script src="{{ asset('assets/orange/js/popper.min.js') }}"></script>
        <script src="{{ asset('assets/orange/js/bootstrap.min.js') }}"></script>
        
        <!-- Slimscroll JS -->
        <script src="{{ asset('assets/orange/js/jquery.slimscroll.min.js') }}"></script>
        
        @yield('scripts')

        <!-- Custom JS -->
        <script  src="{{ asset('assets/orange/js/app.js') }}"></script>
        <script src="{{ mix('js/app.js') }}" defer></script>
    </body>
</html>

resources/views/pages/employee/index.blade.php
<x-app-layout>
    <!-- Page Content -->
    <employee
    list-employee-url="{{ route('employee.list') }}"
    :positions="{{ $positions }}"
    ></employee>
    <!-- /Page Content -->
    @section('style')
        <!-- Select2 CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/select2.min.css') }}">
        
        <!-- Datetimepicker CSS -->
        <link rel="stylesheet" href="{{ asset('assets/orange/css/bootstrap-datetimepicker.min.css') }}">
    @endsection

    @section('scripts')
        <!-- Select2 JS -->
        <script src="{{ asset('assets/orange/js/select2.min.js') }}"></script>
        
        <!-- Datetimepicker JS -->
        <script src="{{ asset('assets/orange/js/moment.min.js') }}"></script>
        <script src="{{ asset('assets/orange/js/bootstrap-datetimepicker.min.js') }}"></script>
        
    @endsection
</x-app-layout>